# Generated by Django 4.1.4 on 2022-12-29 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_2', '0002_alter_services_table'),
        ('payments_2', '0003_rename_expired_payments_expiredpayments_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiredPayments',
            new_name='ExpiredPayment',
        ),
    ]
