# Generated by Django 4.1.4 on 2022-12-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments_2', '0004_rename_expiredpayments_expiredpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpayment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
