# Generated by Django 4.1.4 on 2022-12-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
