# Generated by Django 4.1.4 on 2022-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_2', '0002_alter_services_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='prefijo',
            field=models.CharField(default='NNN', max_length=3),
        ),
    ]
