# Generated by Django 4.1.4 on 2022-12-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_2', '0003_alter_services_prefijo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='prefijo',
            field=models.CharField(default='--', max_length=3),
        ),
    ]
